### ISSUE TITLE
Migrate to API v2

### ISSUE THREAD

**Issue by duggan** [duggan/pontoon#21]
https://www.digitalocean.com/company/blog/api-v2-enters-public-beta/

**Comment by bendtherules** [comment]
Yes, this is important as they will be retiring v1.

**Comment by duggan** [comment]
I'm sort of surprised things have worked as long as they have.

Ok, so EOL for API v1 is **Monday, November 9, 2015.** Good to know.

**Comment by duggan** [comment]
Looks like there's [a popular Python library](https://github.com/koalalorenzo/python-digitalocean) now, Pontoon should probably just wrap that.

**Comment by jamiesonbecker** [comment]
Agreed. also, EOL less than a week away (and can no longer request creds for API v1)

**Comment by duggan** [comment]
Yeah, it's looming. I'll carve out some time for it this week, it'll be a photo finish.

**Comment by duggan** [comment]
Pontoon 0.2.1 is pushed to PyPI (0.2.0 is scrubbed for breaking `configure`). [Changelog here](https://github.com/duggan/pontoon/blob/v0.2.1/CHANGELOG.md). 

Need to update docs, etc, but open an issue if you upgrade to 0.2.1 and notice any problems.

**Comment by jamiesonbecker** [comment]
Excellent, nice work!
