### ISSUE TITLE
CLI doesnt work on windows directly

### ISSUE THREAD

**Issue by bendtherules** [duggan/pontoon#28]
Pontoon put a few scripts inside scripts dir, but they seem to be just the python files without any file extension.

Trying to run configure as  `python .\pontoon-configure` only shows the cli usage docs `Usage: pontoon configure [--help]` and nothing else happens.

Is the cli thing using anything linux specific?

**Comment by duggan** [comment]
I suspect the `configure` command makes a lot of assumptions about being on a POSIX system (particularly SSH key generation, which just shells out to the command line).

Most of the relevant code is in `pontoon/configure.py` and `pontoon/ui.py`.

As [mentioned in the README](https://github.com/duggan/pontoon#windows-support), pontoon does not explicitly support Windows, though I'm sure it's entirely possible to fix what doesn't work.

**Comment by bendtherules** [comment]
Cli doesnt work because files without .py extension but with shebang python in the top are not considered as executables.
So, `pontoon configure` wont work as it is just the `pontoon.py` file without extension. This works on linux though. I think `setup.py` is capable of creating exe scipts directly on windows,as files like `tox.exe` and `pip.exe` are already there in my scipts folder.

**Comment by duggan** [comment]
I think modifying `setup.py` to detect Windows and use different file extensions, etc, should be simple enough. I just wish there was some way to have it testable in Travis.

**Comment by bendtherules** [comment]
No, I think there is a better way to do it with setup.py.

Looks like `console_scripts` is the entry point for this which also generates required exes. I'll give it a shot.

**Comment by duggan** [comment]
:+1:

**Comment by bendtherules** [comment]
#30 should fix this now.

**Comment by bendtherules** [comment]
I'll close this one, but  BATS cli tests should be replaced with something cross-platform as mentioned in #31 . That will ensure that the CLI interface is working just as intended on all platforms.
