### ISSUE TITLE
Doesn't work with Python 3.5(.1)

### ISSUE THREAD

**Issue by gwillem** [duggan/pontoon#42]
Hi & thanks for making pontoon! Most things work with my Python 3, but not all:

I get:
```
$ pontoon configure
[...]
Droplet login username? (currently 'root'): 
write() argument must be str, not bytes

$ pontoon droplet list --detail
dictionary changed size during iteration
```

**Comment by duggan** [comment]
Thanks for the bug report, I remember coming across these when 3.5 was released but forgot to log them.

**Comment by gwillem** [comment]
Thanks a lot for the quick fix!
